# Generated by ./config.exe configure -t unix -v -v (2020-08-09 20:39:11-00:00).

-include Makefile.user

OPAM = opam
DEPEXT ?= $(OPAM) pin add -k path --no-action --yes mirage-unikernel-noop-unix . &&\
	$(OPAM) depext --yes --update mirage-unikernel-noop-unix ;\
	$(OPAM) pin remove --no-action mirage-unikernel-noop-unix

.PHONY: all depend depends clean build
all:: build

depend depends::
	$(DEPEXT)
	$(OPAM) install -y --deps-only .

build::
	mirage build

clean::
	mirage clean

