# Generated by ./config.exe configure -t unix (2020-08-09 21:50:10-00:00).

-include Makefile.user

OPAM = opam
DEPEXT ?= $(OPAM) pin add -k path --no-action --yes mirage-unikernel-hello-unix . &&\
	$(OPAM) depext --yes --update mirage-unikernel-hello-unix ;\
	$(OPAM) pin remove --no-action mirage-unikernel-hello-unix

.PHONY: all depend depends clean build
all:: build

depend depends::
	$(DEPEXT)
	$(OPAM) install -y --deps-only .

build::
	mirage build

clean::
	mirage clean

